[package]
name = "unf"
version = "0.1.0"
authors = ["oscar <oscaroox@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ast = { path = "../../lib/ast" }
scanner = { path = "../../lib/scanner" }
parser = { path = "../../lib/parser" }
interpreter = { path = "../../lib/interpreter" }
ariadne = "0.1.3"